application: gopkgdoc
version: 1
runtime: go
api_version: 1

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /admin/.*
  login: admin
  script: _go_app

- url: /.*
  script: _go_app
