application: gopkgdoc4
version: 2
runtime: go
api_version: go1

handlers:

- url: /google3d2f3cd4cc2bb44b\.html
  static_files: static/google3d2f3cd4cc2bb44b.html
  upload: static/google3d2f3cd4cc2bb44b.html

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /hook/github
  static_files: static/empty.txt
  upload: static/empty.txt

- url: /-/static
  static_dir: static
  expiration: 30d

- url: /.*
  script: _go_app

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (tools/.*)|
 )$
